version: '3'
services:
  web:
    image: nginx
    ports:
      - 443:443
      - 80:80
    working_dir: /code
    volumes:
      - ../api:/code
      - ./images/web/logs:/var/logs/nginx
      - ./images/web/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - db
      - redis
  api:
    build: ./images/api
    working_dir: /code
    volumes:
      - ../api:/code
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  db:
    image: mariadb:10.3.15
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  queues:
    build: ./images/api
    working_dir: /code
    restart: always
    volumes:
      - ../api:/code
    command: php bin/console messenger:consume async --time-limit=3600
    depends_on:
      - api
      - redis
#      ports:
#        - 6001:6001
volumes:
  my-db: